### ISSUE TITLE
Multi line array - declaring function as value

### ISSUE THREAD

**Issue by saltenasl** [ongr-io/ongr-strict-standard#121] opened 2015-05-27 07:28 UTC
```php
            ->add(
                'discount',
                'entity',
                [
                    'label' => 'label,
                    'class' => 'someclass',
                    'query_builder' => function(EntityRepository $er) {
                        return $er->createQueryBuilder('d')
                            ->groupBy('d.id')
                            ->orderBy('d.name', 'ASC');
                    }
                ]
            );
```

```php
                    'query_builder' => function(EntityRepository $er) {
```

This line cannot end with a comma.

**Comment by tautrimas** [comment] 2015-05-27 07:41
Duplicate of #93.

**Closed by tautrimas** 2015-05-27 07:41 UTC
